name: 'entrevista-tascom-api  '
services:
  postgres:
    image: 'postgres'
    container_name: 'entrevista-tascom-api-database'
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: '${DATABASE_USER:-postgres}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD:-postgres}'
      POSTGRES_DB: '${DATABASE_NAME:-postgres}'
